### ISSUE TITLE
Should I .gitignore my serviceAccountKey.json?

### ISSUE THREAD

**Issue by realph** [algolia/algolia-firebase-nodejs#3]
I know you mention this in the README, but I'm trying to deploy to Heroku and I'm getting this error:

    Error: Cannot find module './serviceAccountKey.json'

I know this is because I haven't checked in my `serviceAccountKey.json` (for security I assume...), but how can I get the app to run in Heroku without the `serviceAccountKey.json`??

Sorry if this is a silly question. Thanks in advance!

**Comment by joshed-io** [comment]
Hi @realph, thanks for asking your question, not silly at all! You are right not to check that file in. What you can do instead is set environment variables on Heroku and use those instead of reading the values from a file.

There is a good example of doing this here: [Deploying Firebase App with Service Account to Heroku](https://stackoverflow.com/questions/41287108/deploying-firebase-app-with-service-account-to-heroku-environment-variables-wit).
